# Generated by Django 4.2.15 on 2024-10-28 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solutions",
            name="language",
            field=models.ForeignKey(
                default="unknown",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="solution_language",
                to="problems.language",
            ),
        ),
    ]
