# Generated by Django 4.2.15 on 2024-11-03 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0002_alter_solutions_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solutions",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="task",
                to="problems.tasks",
            ),
        ),
    ]
