# Generated by Django 4.2.15 on 2024-11-04 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0004_alter_solutions_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="tests",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="problems.tests"
            ),
        ),
    ]
