# Generated by Django 4.2.15 on 2024-11-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0007_alter_solutions_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tests",
            name="tests",
            field=models.FileField(upload_to="data_tests/"),
        ),
    ]
