# Generated by Django 4.2.15 on 2024-11-24 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_alter_comments_author_alter_conversation_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="forum.conversation",
            ),
        ),
    ]
